### ISSUE TITLE
S'assurer que requirements.txt marche encore avec l'installation par pip

### ISSUE THREAD

**Issue by MaximeGLegault** [RoboCupULaval/UI-Debug#124]
J'ai essayer d'installer les requirements du requirements.txt avec pip dans un virtual environment et sa n'a pas été capable de downloader PyQt5==5.8. Par la suite j'ai réussi en faisant seulement pip install PyQt5. À ce moment, pip m'installe la version 5.11.3. 

Il faudrait vérifier sur un autre ordinateur si le pip install -r requirements.txt marche.

**Comment by PhiBabin** [comment]
`pip install PyQt5==5.8` marche sur Ubuntu 18.04.1 avec Python 3.6.7 dans un environnement virtuel `venv`. C'est quoi ta version de python et ton OS?

**Comment by MaximeGLegault** [comment]
J'ai rééssayé et ça a plus ou moins marché. J'ai la même erreur qui s'affiche (ne trouve pas quelque chose à downloader), mais ça fini par marcher. Seulement pyqtgraph n'a pas marcher contrairement à la fois précédante.
Anyway, si jamais sa arrive à quelqu'un pour PyQt on peut toujours changer le PyQt5==5.8 to PyQt>=5.8.
Python 3.6.7 sur Ubuntu 18.04.
