### ISSUE TITLE
API Dessin

### ISSUE THREAD

**Issue by jbecirovski** [RoboCupULaval/UI-Debug#13]
Implémentation de l'API dessin :
- [x] Dessiner une ligne
- [x] Dessiner un path
- [x] Dessiner une zone circulaire
- [x] Dessiner un point
- [x] Dessiner une série de point
- [x] Dessiner une zone rectangulaire
- [x] Dessiner une zone de texte
- [x] Dessiner une InfluenceMap
- [x] Dessiner un Arbre (Utilisation RRT)

Option/Filtre de dessin :
- [x] Affiche les dessins d'un ou plusieurs robots
- [x] Limite le nombre de dessin à l'écran
- [x] Limite le temps d'affichage d'un dessin
- [x] Bouton Supprimer tous les dessins

**Comment by ghost** [comment]
Est-ce que le dernier élément est terminé?

**Comment by jbecirovski** [comment]
Not yet !
