### ISSUE TITLE
Interface d'affichage

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/UI-Debug#2]
_(1er juin)_

[ ] Faire afficher le terrain
[ ] Faire afficher les robots détecté par la vision avec leur identification
[ ] Faire afficher la balle
[ ] Élément d'UI de base (boutons, menu, quitter)

**Comment by jbecirovski** [comment]
[ x] Faire afficher le terrain
[x ] Faire afficher les robots détecté par la vision avec leur identification
[x ] Faire afficher la balle
[x ] Élément d'UI de base (boutons, menu, quitter)
