### ISSUE TITLE
Erreur lancement en Windows

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#27]
Sur le tag _beenox-29-juillet_ le lancement en Windows provoque une erreur.
À valider si la version la plus à jour provoque cette erreur.
À reproduire indépendemment, le problème survient sur l'installation de @MaitreMenard

**Comment by ghost** [comment]
Je ne suis **pas** parvenu à répliquer. J'avais cependant les version les plus à jour d'anaconda et pyqt.

**Comment by jbecirovski** [comment]
Pas de retour depuis le mois dernier, je ferme l'issue.
