### ISSUE TITLE
Ajouter un paquet d'initialisation

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#31]
Un paquet générique et avec réponse devrait être ajouté.

L'objectif est pour l'IA de savoir quand envoyé les premières informations (Stratégie/Tactique/Action).
Au démarrage, simplement envoyé le handshake sur le broadcast. Ceci implique de répondre au handshake si réception il y a.

Pas prioritaire.

**Comment by jbecirovski** [comment]
Le HandShake a été rajouté :
- Type 1000 pour IA => UI
- Type 5000 pour UI => IA

Data est un dictionnaire vide.

**Comment by ghost** [comment]
Je vais implémenter le pendant dans l'IA cette fin de semaine. Merci.
