### ISSUE TITLE
Mise à jour graphique interrompu ou saccadé lorsque l'IA roule

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#39]
Sur mon desktop (actuellement limité, cpu pas loin de 100% et carte graphique base puissance), le UI-Debug se met à jour graphiquement (position des robots et autres éléments visuels tiré du serveur de vision) sans aucune latence visible.

Cependant dès que je démarre l'IA, il n'y a plus aucune mise à jour graphique de ces éléments.

**Bien noter que les éléments à dessiner envoyé de l'IA eux sont mis à jour sans problème et très efficacement (pour le contexte)**

Avec les ressources disponibles, GrSim peinent à rouler à plus de 25/30 FPS.

Sur mon portable avec du matériel plus récent et plus décent, la mise à jour est plutôt saccadée.

**Petite hypothèse: est-ce qu'on consomme les frame de vision?**

**Comment by MaximeGLegault** [comment]
J'avais le même problème et j'en ai parlé à Bercerovski. Regarder si l'adresse que Grsim utilise pour envoyer les paquets de vision est la bonne. L'UI-Debug ne fonctionne pas avec localhost 127.0.0.1 il prend 224.5.23.2 dans (Grsim Vision multicast address) à la place. Peut-être que c'est cela le problème.

**Comment by ghost** [comment]
En effet Max, merci.
@jbecirovski: peut-tu prioriser qu'on puisse redéfinir ce paramètre?

**Comment by jbecirovski** [comment]
C'est un problème avec l'objet Vision du RULEngine. Il faut que j'enquête un peu plus en profondeur pour trouver une solution au problème.

**Comment by ghost** [comment]
Vu et lu. Merci Julien.
