### ISSUE TITLE
Commandes humaines

### ISSUE THREAD

**Issue by agingrasc** [RoboCupULaval/UI-Debug#4]
Permettre à un humain de prendre le contrôle directe de l'IA

- [x] Déterminer la cible d'un robot _(1er juin)_
- [x] Déterminer la tactique d'un robot _(8 juin)_
- [x] Déterminer la stratégie de l'IA _(15 juin)_

**Comment by jbecirovski** [comment]
[x ] Déterminer la cible d'un robot (1er juin)

**Comment by agingrasc** [comment]
pour valider, peux-tu maintenant check off directement les boites dans mon post original?
