### ISSUE TITLE
Ajout paquet Frame

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#40]
L'IA devrait pouvoir envoyer les informations du monde pour la frame en cours de traitement.

Ce paquet devrait pouvoir idéalement ce substituer aux frame de vision pour le UI-Debug -- **permettre à l'IA de manipuler ce que le UI "vois"**. Cet élément devrais être une option dans le UI-Debug, choisir la source des informations.

**Comment by jbecirovski** [comment]
Impossible pour le moment avec l'architecture. Il faudrait inclure le FrameModel dans le DataInModel (qui gère les paquets).

Edit: Par contre faire un paquet qui indique le numéro de frame courant, c'est beaucoup plus réaliste.
