### ISSUE TITLE
Ajout paquet info STA actuel

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#41]
Un nouveau paquet pour transférer les informations stratégiques des robots devraient être ajouté.

Ces informations concerneraient un robot en particulier et l'IA en enverrait jusqu'à 12 par frame (un par robot incluant l'équipe adverse).

Proposition de **data**:

{team: str(yellow|blue),
 id: int [0, 5],
 strategy: str,
 tactic: str,
 action: str,
 destination: tuple(int, int),
 kickstrength: int [0, 8]}

J'inclus la stratégie par robot, au cas où éventuellement on modifie le système pour que plusieurs stratégies plus focus se déroulent en simultanée, initialement on peut assumer que l'information sera pareille pour tous (tu peux l'ignorer en somme).

D'un point de vue d'implémentation, est-ce que tu préfères les paquets discrets, où un seul paquet qui groupe les data individuels?

**Comment by jbecirovski** [comment]
C'est mieux un paquet qui regroupe tout:

data = {str(yellow|blue):   { 
                     int(0-5):   { 
                             'tactic': str,             # Correspond à la tactique active sur le robot
                                 'action': str,             # Correspond à l'action active sur le robot
                                 'target': tuple(int, int), # Correspond à la cible active du robot
                                } } }

Pour la valeur du kick va falloir que je vois ce que je fais avec ça.... car dans mon tableau il n'y a pas la place. Peut être devrais-je l'afficher sur le terrain par exemple ?

**Comment by david2194** [comment]
Already done "somehow"
