### ISSUE TITLE
Ajout information équipe dans paquet du contrôleur stratégique

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#42]
Les paquets que le contrôleur stratégique envoie devrait préciser la couleur de l'équipe associée (yellow|blue) et la sélection de stratégie devrait permettre de choisir l'équipe de destination.

Je modifierais tout simplement le dictionnaire de data des deux paquets concernés. Ceci serait très utile dans la perspective où on veut manipuler sans discrimination les deux équipes.

**Comment by jbecirovski** [comment]
Changement des paquets concernés:
- paquet 5002 - set_strategy : {'strategy': str, 'team': str}

Ajout option supplémentaire pour sélectionner l'équipe dans le contrôleur de stratégie.
