### ISSUE TITLE
Ajouts de paramètre pour l'IA à travers le UI

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#43]
L'IA va commencer à acquérir des paramètres diverses pour personaliser son exécution. L'un d'eux est liée à la demande StrategyIA#59 pour changer la fréquence d'exécution de l'IA.

Ces paramètres pourraient être configurés par le UI-Debug en cours d'exécution.

**Comment by david2194** [comment]
Too broad, already done
