### ISSUE TITLE
Commande pour nettoyer filtre et effacer les filtres vides

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#44]
Deux points:
- [ ] Un filtre qui n'a plus d'éléments actif devrait être retiré de la liste des filtres disponibles.
- [ ] Une commande pour reset un filtre devrait être disponible.

Détails concernant le deuxième point: ces commandes doivent être traitées de façon prioritaire, il est possible (et ça va arriver parce que c'est le use case que j'ai en tête) que dans une même frame de l'IA on va envoyer un _clear filter_ et tout de suite une commande pour dessiner un nouveau truc dans ce même filtre. L'implémentation précise est pas très importante, je peux ajouter dans le data le timestamp et tu peux mettre une période de grâce, et je vais essayer minimalement que les commande de clear filtre passent en premier. Mais je lève le point parce que ça va être important!

**Comment by david2194** [comment]
No clue what filters are. Closing for now
