### ISSUE TITLE
Améliorer les paramètres envoyés lors d'une assignation d'une Tactique

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#51]
Lorsqu'on assigne une Tactique, certains paramètres supplémentaires peuvent être nécessaires.
Il faudrait améliorer les paquets lorsqu'on décrit les Tactique disponibles pour aussi indiquer les paramètres nécessaires et des valeurs par défaut intéressantes.

- [ ] Ajouter une description des paramètres et des valeurs par défaut lors de l'initialisation des Tactique
- [ ] Envoyer ces paramètres de façon adéquate lors de l'application d'une Tactique
- [ ] S'assurer d'envoyer la couleur de l'équipe concerné

**Comment by david2194** [comment]
Probably not relevant anymore. Will reopen if needed
