### ISSUE TITLE
Implémenter de reculer la simulation et de l'appliquer dans l'IA

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#52]
Avec les informations STA et du jeu de disponible pour chaque frame, il devient possible de faire reculer la simulation et de réappliquer cet état à l'IA.

Il faut implémenter le paquet d'envoi qui contient toute ces informations et indique à l'IA de reculer la simulation.

**Comment by PhiBabin** [comment]
Par reculé est-ce que c'est "restaurer la state machine STA d'un moment donné"?

**Comment by david2194** [comment]
Va falloir regarder si c'Est encore pertinent et c'est quoi qui est réalistiquement possible de faire avec notre architecture actuelle.
