### ISSUE TITLE
Afficher dans le temps des informations graphique (e.g: paramètre PI)

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#53]
Certaines données fluctuent dans le temps et pourraient être affiché dans un graphique.
Par exemple, les valeurs de l'erreur et de l'accumulateur pour chaque robot dans l'asservissement en position.
Un tel affichage permet de rapidement remarqué des discontinuités dans les commandes.

**Comment by PhiBabin** [comment]
#105
