### ISSUE TITLE
Obtenir et afficher les commandes envoyés aux robots

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#54]
Il faudrait ajouter un paquet pour que le framework envoi aussi les commandes des robots au UI et que ce dernier permettent de les affichers, par exemple en vecteur graphique.

Une option pourrait aussi permettre d'afficher la commande absolu et la commande corrigé pour le robot selon son orientation.

**Comment by david2194** [comment]
Seems to be already done
