### ISSUE TITLE
Pouvoir paramétrer les données réseaux

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#55]
Actuellement, les paramètres réseau ne peuvent pas être modifiés.
Ces derniers devraient pouvoir l'être et ce en temps réel au besoin.
De plus, il serait utile de pouvoir envoyer les paramètres similaire à l'IA.

**Comment by AlexandraMercier** [comment]
2 morceaux:

## Reconfigurer UI Vision
- [x] Adresse IP éditable
- [x] l'info du UI accessible par l'IA
- [x] Real time

## Envoyer la config à l'IA
- [x] Choix du mode: UDP/grSim ou Serial/vrai vie
- [x] Adresse et port multicast pour UDP
- [ ] Pour serial: trouver les devices serials dispos et les lister en dragdown

**Comment by AlexandraMercier** [comment]
Le dragdown pour les devices est dans sa propre issue, la issue #65
