### ISSUE TITLE
Configurer des préférences par défaut et enregistrer ces préférences

### ISSUE THREAD

**Issue by ghost** [RoboCupULaval/UI-Debug#56]
Actuellement, les menu ouvert ou non ont des valeurs par défaut peu utile.
Par exemple, le "Contrôleur de Stratégie" est une fenêtre ouverte 99% du temps.
Il serait préférable qu'elle le soit par défaut ou que du moins on puisse le configurer.

Les configurations devraient pouvoir être enregistré dans un fichier pour pouvoir le distribuer et idéalement sélectionner différentes configurations qui correspondraient à différents flot de travail.
- [ ] Modifier les paramètres par défaut de l'application (_out of the box_)
- [ ] Choisir des paramètres par défaut
- [ ] Enregistrer des paramètres
- [ ] Pouvoir choisir entre différentes configurations (parmi celles enregistrées)

**Comment by david2194** [comment]
Not sure if this is still relevant. Will close for now
