### ISSUE TITLE
Changer comment Stop est appelé dans l'UI

### ISSUE THREAD

**Issue by AlexandraMercier** [RoboCupULaval/UI-Debug#57]
- [ ] tStop -> Stop (implémenté dans StrategyIA)
- [ ] pStop -> DoNothing (implémenté dans StrategyIA)
  tStop et pStop avaient été implémentés avant que des stratégies/tactiques similaires ne soient disponibles dans StrategyIA. Cela va simplifier le code dans StrategyIA.

**Comment by david2194** [comment]
Not relevant anymore
