### ISSUE TITLE
Loggueur bug? message d'erreur quand UIdebug launched apres l'IA, pas de tactiques #just_french_guy_things

### ISSUE THREAD

**Issue by wonwon0** [RoboCupULaval/UI-Debug#72]
Osti de français programeurs!

Y'a un bug 100% repetable quand je launch le UI-debug avant de launch l'ia. Gros message d'erreur (mais le Ui plante pas), le livre de tactique n'est pas loader. Il faut fermer le UIdebug et le relaunch apres l'IA. Si l'ia est arretée mais que le livre de tactique est deja loadé dans le UIdebug, le message d'erreur pop mais on est capable d'envoyer des tactiques quand même CEPENDANT, les points du path, quand on utilise GoToPositionPathfinder, ne s'affichent pas (wtf).

Julien pls fix this... les vrais programmeur doivent être capable de continuer a utiliser ton outil divertissant.

**Comment by PhiBabin** [comment]
@wonwon0  Est-ce que est encore capable de reproduire ce bug ou c'est fix?
