### ISSUE TITLE
Ralentissement après quelques minutes

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/UI-Debug#86]
Après quelques minutes, l'UI-debug devient de plus en plus lent.

**Comment by TwistedSim** [comment]
c'est pas fixed ca?

**Comment by PhiBabin** [comment]
Nope, j'ai profiler (il y a quelques mois) et je n'ai pas trouver la cause.

**Comment by TwistedSim** [comment]
C'était pas le data du truc de replay?

**Comment by PhiBabin** [comment]
Nope, je pensais que ce l'était, mais sa semble juste prendre plus de temps.
Le gros problème est que sa prend beaucoup de temps à reproduire.
