### ISSUE TITLE
Add move of a single robot in grSim from the UI

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/UI-Debug#88]
With the new grSim headless mode (see https://github.com/RoboCup-SSL/grSim/pull/63), it would be preferable if every frequent manupilation that was previously done in grSim, would now be done in UI-Debug. We can currently save a formation of robot, but not move a single robot.

**Comment by SimLemay** [comment]
I suggest shift + click or ctrl + click to move a single selected robot

**Comment by TwistedSim** [comment]
could also be a key on the keyboard like p

**Comment by SimLemay** [comment]
Finally I added ctrl + double right click to move a robot, so : 
double right click : replace the ball
CTRL + double right click : replace a single selected robot
